### ISSUE TITLE
Decouple plotting progress tracker from blockchain sync tracker

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#133]
On `client.ts`, for the function `public async getLocalSegmentCount(): Promise<number>`

Nazar suggested the below as a backlog task:

> This will work, but there are a few issues:
> * `plot_progress_tracker` is a bad name, should be `get_plotted_pieces_count()` or something like that
> * `256` will work for now, but it is not guaranteed to be that way in the future, the actual value must be extracted from the runtime: https://github.com/subspace/subspace/blob/main/crates/sc-consensus-subspace/src/lib.rs#L913
> * as the result of above and considering that you should already be connected to local node anyway I suggest the following:
>     * subscribe to events of local node and monitor for root block archiving that contains archived segment in it, making UI reactive rather than relying on timers
>     * remove `plot_progress_tracker` on backend
>
> Non-blocking, can be done in a separate PR, just don't forget about this.
>
> Thought some more about this. If we care about plotting as such, we do have to inspect the plot and not the chain, but I'm not sure there is a major difference between those right now until we implement DSN sync of the farmer.

Keeping this as an issue to not forget about it

**Comment by rg3l3dr** [comment]
Implementing multi-replica farming will make the plot size configurable by the user and plotting progress will be independent of the blockchain size. However, we sill need to track the status of the blockchain sync from genesis.

- [ ] confirm if or where we can retrieve best block height or size of the chain from the local node over the tauri bridge
- [ ] remove the WS connection from the Vue frontend to the bootstrap node
- [ ] replace with query to the local node
- [ ] implement blockchain sync status bar in the dashboard (initial step is to have a textual UI with block xxxx / xxxx, later we can render this through a graphical progress widget)

**Comment by ozgunozerk** [comment]
@isSerge feel free to close this if the last todo in: https://github.com/subspace/subspace-desktop/issues/133#issuecomment-1113234379 is completed
